// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-whpeJUq6uw2_eeTVqGNN_ty86C-ZrEo',
    appId: '1:684648664774:web:5e19934f80d491756c91c7',
    messagingSenderId: '684648664774',
    projectId: 'farm2fresh-e5be4',
    authDomain: 'farm2fresh-e5be4.firebaseapp.com',
    storageBucket: 'farm2fresh-e5be4.firebasestorage.app',
    measurementId: 'G-TF7NV67JP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl1Cr9SCJz-ImuZdB2EE7XB3vfp-V6hU4',
    appId: '1:684648664774:android:452a227b1aa2949f6c91c7',
    messagingSenderId: '684648664774',
    projectId: 'farm2fresh-e5be4',
    storageBucket: 'farm2fresh-e5be4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAveIviRN9CspglHYCvj8ONJ5Kaeo2BVhU',
    appId: '1:684648664774:ios:3ba8629507d3dc896c91c7',
    messagingSenderId: '684648664774',
    projectId: 'farm2fresh-e5be4',
    storageBucket: 'farm2fresh-e5be4.firebasestorage.app',
    iosBundleId: 'com.example.f2f',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAveIviRN9CspglHYCvj8ONJ5Kaeo2BVhU',
    appId: '1:684648664774:ios:3ba8629507d3dc896c91c7',
    messagingSenderId: '684648664774',
    projectId: 'farm2fresh-e5be4',
    storageBucket: 'farm2fresh-e5be4.firebasestorage.app',
    iosBundleId: 'com.example.f2f',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-whpeJUq6uw2_eeTVqGNN_ty86C-ZrEo',
    appId: '1:684648664774:web:5c23b4f403f7f8fa6c91c7',
    messagingSenderId: '684648664774',
    projectId: 'farm2fresh-e5be4',
    authDomain: 'farm2fresh-e5be4.firebaseapp.com',
    storageBucket: 'farm2fresh-e5be4.firebasestorage.app',
    measurementId: 'G-7RH62E8J2R',
  );
}
